Pytes battery: Add support for native CAN protocol
hoylabs/OpenDTU-OnBattery pull request #1196
Opened 2024-08-25 08:13 UTC by ranma

The recently added PytesCanReceiver.cpp implements the Victron CAN protocol.

This change additionally adds support for the native Pytes CAN protocol messages.

Features only supported in Pytes protocol:
- High-resolution state of charge / full and remaining mAh
- Charge cycle counter
- Balancing state

Features only supported in Victron protocol:
- FW version
- Serial number

Features not yet implemented in Pytes protocol due to lack of docs:
- State/warning flags
- Per-module information when multiple modules are chained

Note that the only known way to select the native Pytes protocol is via the serial console (Cisco-compatible cables work):

```
login config
setprt PYTES
logout
```

to return to Victron protocol use:
```
login config
setprt VICTRON
logout
```

The protocol switch will take effect immediately.

Tested on Pytes E-Box 4850

See https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1188

2024-08-26 06:13 UTC, AndreasBoehm commented
Thanks for your PR, cool that we can get more details about the battery by switching it to a different protocol. 
I will test this once my console cable arrives.

Things that we should adjust:
- Figure out what 'balance' actually represents and add it to the UI
- If we can't figure out state/warning flags we should remove the section from the UI, but it also doesn't feel right for me to switch to a different protocol but then we loose important things like warnings
- Remove any information from the UI that is not available anymore

2024-08-26 08:50 UTC, schlimmchen commented
> Remove any information from the UI that is not available anymore

The UI is generic, as far as I remember. Only info that is put into the respective JSON array is displayed in the UI. So I am not sure why you mention this. We have to take care that in the backend, only relevant info is serialized into JSON. The respective BatteryProvider implementation is responsible for that.

2024-08-26 08:55 UTC, AndreasBoehm commented
@schlimmchen That is exactly what i meant with my comment. Don't touch the UI code, adjust the BatteryStats for 'Pytes' to not add values into the JSON that are not available.

2024-08-29 20:56 UTC, ranma commented
Updated the pull request with support for alarms, warnings and online/offline module count.

2024-08-29 21:24 UTC, AndreasBoehm requested changes

2024-08-29 21:24 UTC, AndreasBoehm commented on src/BatteryStats.cpp
> +    if (_chargeCycles > 0) {
Let's use `-1` as the default value of `_chargeCycles` to replicate how we defined the 'no-data'sate for `_chargedEnergy` and `_dischargedEnergy`

2024-08-29 21:24 UTC, AndreasBoehm commented on src/BatteryStats.cpp
> +    MqttSettings.publish("battery/chargeCycles", String(_chargeCycles));
Should only be published if we have actually have data

2024-08-29 21:24 UTC, AndreasBoehm commented on src/BatteryStats.cpp
> +    MqttSettings.publish("battery/balance", String(_balance));
Should only be published if we have actually have data

2024-08-29 21:24 UTC, AndreasBoehm commented on src/BatteryStats.cpp
> +    if (_chargeCycles > 0) {
Please also add 'balance' to the LiveView

2024-08-29 21:24 UTC, AndreasBoehm commented on src/PytesCanReceiver.cpp
> +            // bool chargeHigh = this->getBit(mergedBits, 5);
What about the commented bits?

2024-08-29 21:24 UTC, AndreasBoehm commented on src/PytesCanReceiver.cpp
> +            _stats->_alarmOverTemperature = stateDischarging && overTemp;
what about `stateIdle`?

2024-08-29 21:24 UTC, AndreasBoehm commented on src/PytesCanReceiver.cpp
> +            uint8_t soc = static_cast<uint8_t>(this->readUnsignedInt16(rx_message.data));
i think we can omit parsing the soc if we don't use it

2024-09-01 19:36 UTC, ranma commented
With this change and Victron protocol:
![screenshot victron](https://github.com/user-attachments/assets/0ee9ea80-1e8d-4830-84ce-ff96607d7d99)

With this change, Pytes protocol and low charge state:
![screenshot pytes low charge](https://github.com/user-attachments/assets/a36c7729-3349-406c-b833-618857788a37)

With this change, Pytes protocol, fully charged and balancing active:
![screenshot pytes fully charged and balancing](https://github.com/user-attachments/assets/46ab3597-3ae7-4af2-9f10-681450a59d4b)

2024-09-05 18:32 UTC, ranma commented
Added HASS auto-discovery for new fields.

2024-09-16 16:36 UTC, AndreasBoehm commented
@ranma could you do me a favor and update the description of the PR to reflect what features/changes we can expect from this PR?
Its a bit hard to follow the comments and the code does not match the description anymore (e.g. support of alarms)

Thank you.

2024-09-16 16:54 UTC, AndreasBoehm requested changes

2024-09-16 16:54 UTC, AndreasBoehm commented on src/PytesCanReceiver.cpp
> +static void pytesSetCellLabel(String& label, uint16_t value) {
we are reading `uint8` from the can message but here you defined `uint16`?

2024-09-16 16:54 UTC, AndreasBoehm commented on src/PytesCanReceiver.cpp
> +            pytesSetCellLabel(_stats->_cellMaxTemperatureName, this->readUnsignedInt8(rx_message.data + 4));
pytes protocol reports the name as an int and victron as a string?
I am wondering why we need to use different methods to get the name as a string.

2024-09-16 16:54 UTC, AndreasBoehm commented on src/PytesCanReceiver.cpp
> +            bool dischargeEnabled = rx_message.data[1];
We should use this information and not throw it away, if we need it, because with the victron protcol we don't  get the values like that, but we get a count of modules that are blocking charge or blocking discharge. Does something similar exist for the message `0x40b`? Right now we only parse module count online and offline.

I know that the comment is not directly related to this line of code but also: https://github.com/helgeerbe/OpenDTU-OnBattery/pull/1196/files#diff-fdc211e7100fe5cfbe1c29df40fefa664212330184f5ec0394748fe4637808ceR455

2024-09-16 16:54 UTC, AndreasBoehm commented on src/PytesCanReceiver.cpp
> +            bool dischargeEnabled = rx_message.data[1];
Right now we show 0 for both `Charging blocked` and `Discharging blocked` under `Battery modules` even though we don't populate this field when the pytes protocol is used

2024-09-17 09:04 UTC, AndreasBoehm commented
I switched to the PYTES protocol and the web ui is showing a strange value for `voltage` sometimes, the value shown was `1,70 V`. In the live view on top and in the battery card on the bottom.

It happens randomly and i could not find anything strange in the CAN messages, they all looked fine and showed the correct voltage of 53,xx

Did you have the same experience @ranma ?

2024-09-20 10:35 UTC, ranma commented on src/PytesCanReceiver.cpp
> +static void pytesSetCellLabel(String& label, uint16_t value) {
Oops, that should have been readUnsignedInt16() where this is called.
One byte is the cell id, the second byte is presumably the module id (though I only have a single module, so I can't easily verify that currently).

2024-09-20 10:37 UTC, ranma commented on src/PytesCanReceiver.cpp
> +            pytesSetCellLabel(_stats->_cellMaxTemperatureName, this->readUnsignedInt8(rx_message.data + 4));
Correct. In victron protocol the battery converts to string internally, e.g.:
```
  case 9:
                    /* msg 0x374 */
    bVar8 = *(byte *)&batteryState->field35_min_cell_mv_id;
    *pbVar7 = bVar8 / 10 + 0x30;
    pbVar7[1] = bVar8 % 10 + 0x30;
    uVar9 = (uint)batteryState->field35_min_cell_mv_id >> 8 & 0xff;
    cVar1 = (char)(uVar9 / 10);
    pbVar7[2] = cVar1 + 0x30;
    pbVar7[3] = (char)uVar9 + cVar1 * -10 + 0x30;
    pbVar7[4] = 0;
    pbVar7[5] = 0;
    pbVar7[6] = 0;
    pbVar7[7] = 0;
    return 8;
```

2024-09-20 10:41 UTC, ranma commented
> I switched to the PYTES protocol and the web ui is showing a strange value for `voltage` sometimes, the value shown was `1,70 V`. In the live view on top and in the battery card on the bottom.

I don't remember seeing any drops like that, not in the UI nor in the MQTT data.

2024-09-20 19:31 UTC, ranma commented on src/PytesCanReceiver.cpp
> +            bool dischargeEnabled = rx_message.data[1];
Ah, yes. I though I had updated the code already at some point, maybe I accidentally reverted that.

FWIW I've repeatedly updated this comment with the protocol details: https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1188#issuecomment-2307087491

> Does something similar exist for the message 0x40b

Its part of message 0x408, which has a bitfield which indicates which modules have charge inhibited (byte 5) / discharge inhibited (byte 6).

2024-09-22 18:08 UTC, ranma commented
> I switched to the PYTES protocol and the web ui is showing a strange value for `voltage` sometimes, the value shown was `1,70 V`. In the live view on top and in the battery card on the bottom.

I can currently reproduce this in testing right now, I sometimes see `2.90 V` instead of `53.15 V`.

2024-09-22 18:22 UTC, ranma commented
> I can currently reproduce this in testing right now, I sometimes see `2.90 V` instead of `53.15 V`.

There was a stray setVoltage() fatfingered into the message 0x402 handler at some point, removed that to fix the issue.

Also verified the charge inhibited count with replayed messages from when the battery was full, it shows `Charging blocked     1` now:
![image](https://github.com/user-attachments/assets/75135948-14a7-49fa-99cf-488ffefefc67)

2024-09-23 14:22 UTC, AndreasBoehm commented on src/PytesCanReceiver.cpp
>              _stats->_totalCapacity = this->readUnsignedInt16(rx_message.data);
I think this is only available in the Victron protocol, right?

2024-09-23 15:25 UTC, ranma commented on src/PytesCanReceiver.cpp
>              _stats->_totalCapacity = this->readUnsignedInt16(rx_message.data);
Its there for Pytes protocol:
```
        case 0x409: { // Pytes protocol: full mAh / remaining mAh
            _stats->_totalCapacity = this->scaleValue(this->readUnsignedInt32(rx_message.data), 0.001);
```

2024-10-10 16:04 UTC, merged