Jbd bms support
hoylabs/OpenDTU-OnBattery pull request #1218
Opened 2024-09-01 14:07 UTC by MoleBre

First of all: also my thank to all the developers. You are doing a great job. This project is awesome.
Please be patient with my skills. Its my first time contributing to a project on github and it took me some time to understand the code more or less :-).

I copied the the jk-bms code and adapted it to the [jbd-bms uart communication protocol](https://cdn.shopifycdn.net/s/files/1/0606/5199/5298/files/JDB_RS485-RS232-UART-Bluetooth-Communication_Protocol.pdf?v=1682577935) as specified by the manufacturer.

The code is working with my setup via the rs485 interface of my jbd bms:
- [JBD Smart BMS 8~21S](https://jiabaida-bms.com/products/jbd-smart-bms-8s-24v-100a-lithium-battery-protection-circuit-board-with-passive-balance-temp-sensor?variant=43846911131810)
- esp32-s3-n16r8-wroom1 + [TTL RS-485 Konverter Modul Max485 Adapter](https://www.makershop.de/module/kommunikation-module/ttl-rs-485/)

This pull request is related to issue #467.

![BatterySettings](https://github.com/user-attachments/assets/089c630a-0d1e-4c77-8aef-c236eaefd675)
![LifeView-LifeData](https://github.com/user-attachments/assets/c8217b8d-b979-4fe3-a42d-c799d0b5482b)
![LifeView-LifeData-JBD-BMS](https://github.com/user-attachments/assets/5d0172e0-4937-4db7-a7e0-d64db9cb21cd)

2024-09-07 20:49 UTC, schlimmchen commented
Thanks for this contribution!

I looked at this some time ago and noticed that it needs some polishing. Minor stuff (commented code should be cleaned up, spaces/indention).

The other thing that is a little bit offputting is this:

> I copied the the jk-bms code

However, I am not sure if I am willing to put in the time and effort to generalize and share code. It would be the right thing to do, though. I can also see that there are significant differences, so clearly, there will be a lot of new code. We could generalize the DataPointContainer using a template (the DataPoint's std::variant go into the template parameters, and the DataPointContainer needs at least the label as template parameter...). I think that would be a good idea.

You marked this as draft a couple of hours ago. Why is that? because of the conflicts in webapp_dist? Just clean webapp_dist and you are good, at least regarding the conflicts.

2024-09-08 10:58 UTC, MoleBre commented
Hi Schlimmchen. Ich antworte mal kurz auf Deutsch.

Vielen Dank erstmal für deine Rückmeldung!

Den PR-Status "Draft" und "Open" hatte ich falsch verstanden. Ich habe es jetzt wieder auf "Open" zurückgeändert.

Ja, da hast du recht. Den Code aufzudoppeln ist nicht schön. Anders hätte ich deinen Jk-Bms Code jedoch anpassen müssen, damit ich ihn für das Jbd-Bms wiederverwenden kann. Das habe ich mich bei meinem ersten PR nicht getraut. Ich habe hier kein Jk-Bms zum testen und ich wollte keine Bugs in euren bestehenden Code einbauen. Das Risiko war mir zu hoch. 

Ich habe die Test-Kommentare gelöscht und den Commit mit den Webapp-Files zurückgenommen. Die falschen Einrückungen konnte ich aber bei mir in VS Code nicht finden. 

Gebe mir gerne Bescheid, wenn ich noch etwas anpassen soll.

BG.

2024-09-13 19:22 UTC, schlimmchen requested changes
I'll tackle the required changes.

2024-09-13 19:22 UTC, schlimmchen commented on src/JbdBmsController.cpp
> +            }
This else could be removed and the return statement unindented. Very minor.

2024-09-13 19:22 UTC, schlimmchen commented on src/JbdBmsController.cpp
> +            }
This else could be removed and the return statement unindented. Very minor.

2024-09-13 19:22 UTC, schlimmchen commented on webapp/src/locales/de.json
> +        "ProviderJbdBmsSerial": "Jiabaida (BJD) BMS per serieller Verbindung",
There's a typo: BDJ

2024-09-13 19:22 UTC, schlimmchen commented on webapp/src/locales/de.json
> +        "JbdBmsConfiguration": "JBD BMS Settings",
Not translated to German.

2024-09-13 19:22 UTC, schlimmchen commented on webapp/src/views/BatteryAdminView.vue
> +                </div>
This should be generalized.

2024-09-13 19:22 UTC, schlimmchen commented on src/BatteryStats.cpp
> +        // "old" topic.
As the comment suggests, the battery voltage is not skipped to avoid a regression. Since this is a new feature, we shall not publish the battery voltage a second time, so skip the respective label here.

2024-09-13 19:22 UTC, schlimmchen commented on src/JbdBmsDataPoints.cpp
This really is a 1:1 copy of `JkBmsDataPoints.cpp`. That's crazy. We need to find a way to generalize this.

2024-09-13 19:22 UTC, schlimmchen commented on include/JbdBmsDataPoints.h
The DataPoint and DataPointContainter classes are indeed 1:1 copies. This must be generalized to avoid code duplication.

2024-09-13 21:32 UTC, schlimmchen commented
Rebased onto current development and de-deplicated `DataPointsContainer`.

2024-09-13 22:08 UTC, schlimmchen commented
@MoleBre Ich wollte mergen, als mir aufgefallen ist, dass die HASS autodiscovery fehlt. Kannst du da bitte zumindest die wichtigsten Werte nacharbeiten? Siehe `MqttHandleBatteryHass.cpp`.

2024-09-14 20:32 UTC, schlimmchen commented
~~Zwei~~ Drei Dinge sind hier noch zu tun: (1) HASS autodiscovery und (2) der Battery Provider Index muss 6 werden um #1199 auszuweichen und (3) es muss nach dem Mergen von #1199 nochmal ge-rebase't werden, wobei Konflikte zu beheben sein werden.

2024-10-30 20:53 UTC, schlimmchen commented
Tested successfully against a SP22S003AL22S40A with firmware version 6.7

Issues:
* BatteryOneTemperature is actually the board's temperature. This might be specific to my model, so I am not changing it.
* There should be a third temperature sensor value, but it seems it is not communicated over the serial connection.
* Currents below ~800mA are not detected by the BMS at all (not an OpenDTU-OnBattery problem, just an observation).
* Could not test all alarms, but some, and also multiple at once.
* Did not check all HASS values, but some, and I assume the rest are good (maybe there is a typo somewhere...)

2024-10-30 20:53 UTC, merged