[DPL] Overscaling: Support for HMT inverters
hoylabs/OpenDTU-OnBattery pull request #1286
Opened 2024-09-26 17:26 UTC by vaterlangen

This MR adds support for inverters, having multiple channels sharing one MPPT. This is achieved by combining all channels assigned to one MPPT before calculating any correction factors. The assignment between channels and MPPTs is added directly to the converter definition. For all inverters, that are already supported today, there should be no functional change, as the numb er of channels per MPPT is exactly one. The assignment of channel(s) to MPPT is currently calculated on every call - but I can also add some kind of caching for that.

If this approach is fine for you, I would try to get the changes of the Hoymiles library merged into the parent project.

I'm running custom build with these changes in my own setup (single HMT-2250) since a few days - and DPL seems to be stable.

@schlimmchen The MR targets your branch from #1216

2024-09-27 19:06 UTC, schlimmchen requested changes
@AndreasBoehm will have to approve this.

2024-09-27 19:06 UTC, schlimmchen commented on lib/Hoymiles/src/inverters/HERF_1CH.cpp
>  static const byteAssign_t byteAssignment[] = {
can you please convince me that hijacking the byteAssignment arrays is the best approach? my feeling tells me it would be much better to introduce a separate data structure which maps CH0, CH1, etc. to MPPT_* enum values. That would drastically reduce the size of the changeset, and reduce runtime in the functions you added, which now iterate the whole byteAssignment.

2024-09-27 20:28 UTC, vaterlangen commented on lib/Hoymiles/src/parser/StatisticsParser.h
> +// MPPT_NONE is sued for non string values
Yes, correct

2024-09-27 20:44 UTC, vaterlangen commented on lib/Hoymiles/src/inverters/HERF_1CH.cpp
>  static const byteAssign_t byteAssignment[] = {
I think, I can't. 

You are absolutely right, processing time is a weak point of the implementation. Especially for HMT 6T this will cause about 60 to 100 cycles for each call. When implementing this first approach,   I just adopted the getChannels() mechanism. 

I already thought about adding some extra structure - which would mean additional work (and without knowing about the future of the MR I decided to postpone it). The downside of using a additional structure, is that there are two places to be adopted when implementing new inverters.  Processing time with the current approach could be drastically reduced by using some caching mechanism, so the assignment has to be calculated only once when constructing the object.

If the other adjustments are fine and this MR just needs the above adjustments to get merged, I'm absolutely fine with adopting the mechanism.

2024-09-30 20:19 UTC, vaterlangen commented on lib/Hoymiles/src/inverters/HERF_1CH.cpp
>  static const byteAssign_t byteAssignment[] = {
I now checked some other solutions, focused on size and processing time. V1 is the initial version (all solutions can be found in my fork)

Comparison of `firmware.bin` for the different solutions:
```
$ ls -la hmt_overscaling_v* | sort
-rw-r--r-- 1 fabian fabian 1972160 30. Sep 19:14 hmt_overscaling_v3.bin
-rw-r--r-- 1 fabian fabian 1972320 30. Sep 19:25 hmt_overscaling_v1.bin
-rw-r--r-- 1 fabian fabian 1974320 30. Sep 19:20 hmt_overscaling_v2.bin
```
As I think we should go with v3, I will update this branch/MR.

2024-09-30 20:28 UTC, vaterlangen commented on lib/Hoymiles/src/parser/StatisticsParser.h
> +    std::list<ChannelNum_t> getChannelsByMppt(const MpptNum_t mppt) const;
sure, you are right.

2024-10-10 16:31 UTC, AndreasBoehm commented
@schlimmchen as this PR is pointing to your branch and we have another PR https://github.com/hoylabs/OpenDTU-OnBattery/pull/1298 that is going to modify the shading code i am not sure how we want to proceed with this.

It will be a nightmare to manage changes in both places. For you and for me.

Should we hold this back until multiple inverter support is final or should we try to get the other shading adjustments merged to your branch as well?

2024-10-10 16:33 UTC, AndreasBoehm requested changes

2024-10-10 16:33 UTC, AndreasBoehm commented on lib/Hoymiles/src/inverters/InverterAbstract.h
> +    MPPT_CNT
`MPPT_CNT` is never used, do we need it?

2024-10-10 16:33 UTC, AndreasBoehm commented on lib/Hoymiles/src/inverters/InverterAbstract.cpp
> +std::vector<ChannelNum_t> InverterAbstract::getChannels() const
Should we call this `getChannelsDC()` to better reflect that this only returns DC channels?

2024-10-10 16:33 UTC, AndreasBoehm commented on lib/Hoymiles/src/inverters/InverterAbstract.cpp
> +std::vector<ChannelNum_t> InverterAbstract::getChannelsByMppt(const MpptNum_t mppt) const
Should we call this `getChannelsDCByMppt()` to better reflect that this only returns DC channels?

2024-10-10 16:33 UTC, AndreasBoehm commented on lib/Hoymiles/src/inverters/HM_4CH.cpp
> +    return sizeof(channelMetaData) / sizeof(channelMetaData[0]);
can you explain what `/ sizeof(channelMetadata[0]` is doing?

2024-10-10 16:33 UTC, AndreasBoehm commented on lib/Hoymiles/src/inverters/HM_4CH.cpp
> +uint8_t HM_4CH::getChannelMetaDataSize() const
Could we put a default implementation into `InverterAbstract` instead of duplicating code?

2024-10-10 18:27 UTC, schlimmchen commented
> It will be a nightmare to manage changes in both places. For you and for me.

[Nah, it'll be fine](https://www.youtube.com/watch?v=6uFQMKW53I4) :wink:

I suggest that #1298, once it is ready, is merged first. I can rebase #1216 onto it, that should not be a big deal. However, then merging this changeset with the updated #1216 could be a challenge. And this feature will then only be available together with #1216. @vaterlangen Would that be an issue for you? I guess not, as you decided to implement this feature against #1216 in the first place?

The way I see it, trying any other way will be even harder and more error-prone.

2024-10-12 18:52 UTC, vaterlangen commented on lib/Hoymiles/src/inverters/InverterAbstract.h
> +    MPPT_CNT
Correct, we don't need it at the moment. As it is also in place on the other the structs, I oriented on the existing coding style (with the hope, that there will be less complaints when porting this to OpenDTU) and also added it. As it is only a enum definition, the additional entry should not do any harm.

2024-10-12 18:54 UTC, vaterlangen commented on lib/Hoymiles/src/inverters/InverterAbstract.cpp
> +std::vector<ChannelNum_t> InverterAbstract::getChannelsByMppt(const MpptNum_t mppt) const
good point, updated it

2024-10-12 18:54 UTC, vaterlangen commented on lib/Hoymiles/src/inverters/InverterAbstract.cpp
> +std::vector<ChannelNum_t> InverterAbstract::getChannels() const
good point, updated it

2024-10-12 19:14 UTC, vaterlangen commented on lib/Hoymiles/src/inverters/HM_4CH.cpp
> +    return sizeof(channelMetaData) / sizeof(channelMetaData[0]);
tldr: Calculating number of elements at compile time

* `sizeof(channelMetaData[0]) ` returns the number of bytes occupied by the **first element** in the array (same as  `sizeof(channelMetaData_t)` - but duplicating the type here would be more error prone without any benefits)
* `sizeof(channelMetaData)` returns the number of bytes occupied by the whole array (aka. **all elements**)
* If we divide the size of the array (containing all elements) by the size of a single element, we will get the number of elements
* As `sizeof()` is evaluated to a constant value at compile time, the compiler can do constant folding, resulting in a constant value
* It would be more clear, if I would add `constexpr` to the function - but then we would have to update to C++20 (constexpr on virtual functions)

2024-10-12 19:16 UTC, vaterlangen commented on lib/Hoymiles/src/inverters/HM_4CH.cpp
> +uint8_t HM_4CH::getChannelMetaDataSize() const
No, as `channelMetaData` is a private member of the child class. We could do some casting or template magic to get access to it from the parent class, but IMHO that is ugly and error prone. If you know a clean way to do this, please tell me :)

2024-10-12 19:25 UTC, vaterlangen commented
@schlimmchen I'm absolutely fine with it - that's why I targeted your feature branch #1216. 

I'm currently running `feature/zendure_solarflow+dpl-multiple-inverters-pr+hmt_overscaling_v3` - so if this is included in your branch, I would not have to keep it updated, too ;)
Would also be great, if #1216 would be merged to devel, as I would like to fully integrate the Soloarflow battery into DPL

2024-10-12 19:32 UTC, vaterlangen commented
@schlimmchen / @AndreasBoehm If you want me to also tackle the linter complaints on the existing stuff, please tell me

2024-10-13 18:06 UTC, schlimmchen commented
> If you want me to also tackle the linter complaints on the existing code, please let me know

@vaterlangen Nope. This PR is currently running cpplinter with version 2, because the version was not fixed and version 2 was released recently. Once #1216 and this are rebased onto the current development branch, cpplint will run with version 1.6.1 again. It will not complain about old-style casts. I don't like them either, but I am not motivated to tackle them right now, so we use the "old" cpplint for now.

2024-10-18 21:10 UTC, vaterlangen commented
Rebased to current `dpl-multiple-inverters-pr`

2024-10-22 16:31 UTC, AndreasBoehm approved these changes

2024-10-22 16:32 UTC, AndreasBoehm commented
Changes approved, looks good to me.

2024-10-22 17:57 UTC, schlimmchen approved these changes
My approval is based on Andreas approval.

2024-10-22 18:00 UTC, merged

2024-10-22 18:06 UTC, schlimmchen commented
@AndreasBoehm @vaterlangen I assume this will blow up in our faces (as it should) when Thomas adds support for a new class of inverters, such that we are forced to implement `getChannelMetaData()` and `getChannelMetaDataSize()` and we won't forget it? I am pretty sure, but still I wanted to clarify.

Ah, come on... I missed something: The methods in the derived classes are neither override nor final, not even virtual. That's not ideal (for readability). I'll add the final keyword in #1216.

2024-10-22 21:55 UTC, vaterlangen commented
Yes, I guess the compiler will be really unhappy if these functions are missed out on an inverter class ;)
If anything arises here, don't hesitate to contact me (if I don't see it in time).

I would try to get these changes on the inverter classes merged to OpenDTU, too - or did you already talk to Thomas about this?

2024-10-23 06:16 UTC, schlimmchen commented
> If anything arises here, don't hesitate to contact me (if I don't see it in time).

Thanks, will do.

> I would try to get these changes on the inverter classes merged to OpenDTU, too

Go ahead. However, I am not sure if the upstream project gets anything out of the added info?

> or did you already talk to Thomas about this?

Nope.