Update overscaling for better mixed setup management.
hoylabs/OpenDTU-OnBattery pull request #1298
Opened 2024-09-29 19:03 UTC by leoai-81

I've mostly based this work considering HMS1600 and Marstek battery (externally managed). It tries to overscale no matter the number of shaded channels. Shaded factor added as variable as it can depends on how many channels are subject to shade vs others. Will likely continue to work on it in the future, giving very promising results in terms of adaptation to load changes. Future development could be to integrate control of Marstek B2500 loadfirst/passthrough setting for given timeperiods to accomodate different expositions and solar + battery in the same setup.

2024-10-10 17:12 UTC, AndreasBoehm requested changes
Please also fix the issues that cpplint and yarn prettier reported

2024-10-10 17:58 UTC, leoai-81 commented
Ha prettier, that was it. I was wondering what was the code format for the vue files. Should be fine now, can you run the workflows again ?

2024-10-10 18:09 UTC, schlimmchen requested changes
This changeset has serious issues.

2024-10-10 18:09 UTC, schlimmchen commented on src/PowerLimiter.cpp
> +        auto overScaledLimit = static_cast<float>((newLimit - static_cast<int>(shadedChannelACPowerSum)) / (static_cast<float>(dcNonShadedChnls)/static_cast<float>(dcTotalChnls)));
meh... not critical, but this line should be three lines, with two variables accurately describing what the dividend and divisor are.

2024-10-10 18:09 UTC, schlimmchen commented on src/PowerLimiter.cpp
> -
wait... what? if this change should make it into the project, we need a clear reason/motivation, a respective change in the documentation, etc... why are we suddenly restarting solar-powered inverters? because you are treating yours as such, even though it is actually connected to a battery? sorry, it does not work this way. if you need overscaling even though your inverter is battery-powered, we need to find a way to set this up properly. this is not okay.

2024-10-10 18:09 UTC, schlimmchen commented on webapp/src/views/PowerLimiterAdminView.vue
> +                    :tooltip="$t('powerlimiteradmin.ShadedFactor')"
why is the label the same as the tooltip?! use a short label. I see in the locales that the label text is far too long.

2024-10-10 18:09 UTC, schlimmchen commented on webapp/src/locales/de.json
> +        "ShadedFactor": "Factor to consider if panels are shaded 0-100, in % vs expected channel power",
@AndreasBoehm Is is okay that I don't understand what this does or must this be explained further, maybe in the docs?

2024-10-10 18:09 UTC, schlimmchen commented on src/WebApi_powerlimiter.cpp
> +    config.PowerLimiter.ShadedFactor = root["shaded_factor"].as<int32_t>();
mixed indent. was correct, now is wrong... the replaced line has a tab, even though all others have spaces, and even the new line has spaces.

2024-10-10 19:18 UTC, leoai-81 commented on src/PowerLimiter.cpp
> -
Well, good point. Right now the restart function allows you not to restart if you want. So blocking this from code for solar powered inverter makes no sense. Coming to this effort, you're looking at a mixed setup (panels / nothing, panels / battery, different orientation of panels per mppt...). Battery management being fully external, you do not need to rely on the work done for battery management, therefore considering it as "solar powered".

2024-10-10 19:26 UTC, leoai-81 commented on webapp/src/views/PowerLimiterAdminView.vue
> +                    :tooltip="$t('powerlimiteradmin.ShadedFactor')"
Good point, thanks.

2024-10-10 19:29 UTC, leoai-81 commented on webapp/src/locales/de.json
> +        "ShadedFactor": "Factor to consider if panels are shaded 0-100, in % vs expected channel power",
It's just the percentage for which you consider the channel "shaded". Ie. if a channel provides 90% of the desired output, then you consider it as fully producing. Previously was was a fixed value of 98%. But that's totally arbitrary and that can greatly change depending on installation.

2024-10-11 06:33 UTC, AndreasBoehm commented on webapp/src/views/PowerLimiterAdminView.vue
> +                    placeholder="60"
placeholder should match the default value of 98%

2024-10-12 10:46 UTC, AndreasBoehm commented on webapp/src/locales/de.json
> +        "ShadedFactor": "Factor to consider if panels are shaded 0-100, in % vs expected channel power",
Could you work on that text a bit @leoai-81 ?
For me its also hard to understand, even though i know what its about.

2024-10-12 18:14 UTC, schlimmchen commented on src/PowerLimiter.cpp
> -
> Battery management being fully external, you do not need to rely on the work done for battery management

You can effectively disable "battery management" by setting the start and stop thresholds to very small values. So you can treat your inverter as battery-powered. You then lose overscaling...

So you want to enable overscaling regardless of whether or not the inverter is solar- or battery-powered. This can make sense, as I am planning to implement a linear overscaling for underperforming battery-powered inverters in #1216. However, that is not the kind of overscaling you want when you mark the inverter as battery-powered... Oh boy...

You know what: Maybe this change isn't so bad. I won't have an effect on actual solar-powered inverters, since they are unreachable in the middle of the night. Ah! Let's make this if-statement `if (inverter->isReachable())` (or similar) and only return in the `if`'s body? That would solve your problem, it would still make sense, and has a low risk of introducting a regression -- I think.

@AndreasBoehm Does this make sense to you?

Hm, another thing: How did you enable restarting the inverter in the first place? The setting is hidden in the web UI when you enable "solar-powered inverter". So that would need to change. And, as I wrote already, the docs must be updated.

2024-10-12 18:15 UTC, schlimmchen commented on src/PowerLimiter.cpp
> +            dcNonShadedChnls=1;
Why did you mark this as resolved? There are still spaces missing around the equal sign.

2024-10-12 18:16 UTC, schlimmchen commented on webapp/src/locales/de.json
> +        "ShadedFactor": "Shading factor %",
You already set Postfix="%", which is correct, so the unit shall be removed from the label. We don't do units in labels anyhwere.

2024-10-12 18:19 UTC, schlimmchen commented on src/PowerLimiter.cpp
> +        auto factor_shaded = static_cast<float>(config.PowerLimiter.ShadedFactor)/static_cast<float>(100);
snake_case? Please change to camelCase.

2024-10-15 17:07 UTC, leoai-81 commented on src/PowerLimiter.cpp
> -
@schlimmchen , well, on what I can comment... Battery scaling is not immediate, meaning that a -shot- surge (ie, 30sec) in power need will always introduce some loss one way or another... Either by "not patching up quick enough (up or down)" or by patching up "too aggressively"...

2024-10-15 17:14 UTC, leoai-81 commented on webapp/src/locales/de.json
> +        "ShadedFactor": "Shading factor %",
Fine

2024-10-16 16:29 UTC, AndreasBoehm commented on webapp/src/locales/de.json
> +        "ShadedFactor": "Factor to consider if panels are shaded 0-100, in % vs expected channel power",
What about `Set the minimum power output threshold (%). Channels below this percentage are considered shaded and excluded from scaling.` ?

2024-10-17 06:53 UTC, AndreasBoehm commented on src/PowerLimiter.cpp
> +        auto newLeanLimit = static_cast<float>(newLimit - static_cast<int>(shadedChannelACPowerSum));
Won't it result in a wrongly calculated new limit if you always consider one channel as non-shaded but still have the AC-power of that channel within this calculation?

Thats actually different from what the 'old' calculation did

2024-10-17 06:54 UTC, AndreasBoehm commented on src/PowerLimiter.cpp
> -
@schlimmchen makes sense to check if the inverter reachable to allow the restart

2024-10-22 16:21 UTC, AndreasBoehm commented
@leoai-81 are you able to push the requested changes? If not, are you fine with me taking care of adjusting this PR?

2024-10-23 07:12 UTC, leoai-81 commented
@AndreasBoehm , yes, should be able to push what's been discussed today

2024-10-24 19:02 UTC, leoai-81 commented on webapp/src/locales/de.json
> +        "ShadedFactor": "Factor to consider if panels are shaded 0-100, in % vs expected channel power",
Sure, can settle on that one. Should be aligned with latest branch update.

2024-10-24 19:18 UTC, leoai-81 commented on src/PowerLimiter.cpp
> +        auto newLeanLimit = static_cast<float>(newLimit - static_cast<int>(shadedChannelACPowerSum));
Yes, that's indeed different. You're in a scenario where the system outputs way less power than what you'd expect. So one of the channel becomes the only hope of the inverter to provide that power... Should you directly set it to max power ? I did not want it to be so. This way, the power limit will gradually increase so hopefully one of the channel will bring balance to the overall system. The more the actual power diverges from asked, the higher the inverter limit will be. The closer the actual power is from what's asked, the closer the inverter limit will be.

So yes, if you ask 200w, your inverter produces 10... your limit will become the max possible (1600w in my HMS case)... Do you care ? No. As soon as the power produced will get closer to what's asked, the limit will also get closer to that (more or less abruptly depending of shaded channels vs total).

2024-11-05 20:57 UTC, leoai-81 commented
Hi @AndreasBoehm , any chance to see that merged ? Thanks.

2024-11-06 07:00 UTC, AndreasBoehm commented
Hi @leoai-81, there are open comments from @schlimmchen that need to be addressed before i do another round of review. Thanks

2024-11-26 20:43 UTC, closed without merging

2025-01-10 07:40 UTC, AndreasBoehm commented
Parts of your work made into our latest release. Thank you!
https://github.com/hoylabs/OpenDTU-OnBattery/releases/tag/2025.01.09