Add optional "load current" to live view, MQTT and HASS.
hoylabs/OpenDTU-OnBattery pull request #1367
Opened 2024-11-01 15:57 UTC by SW-Niko

- add optional "load current" to live view, MQTT and HASS.
- change "load output" to optional handling
Charge controller with physical "load output" will publish "load output state" and "load current"
Charge controller without physical "load output" but configured "virtual output" will publish just "load output state"
Charge controller without physical "load output" and not configured "virtual output" will not publish "load output state" and "load current"

2024-11-01 15:59 UTC, SW-Niko commented
Based on issue #947

2024-11-01 20:37 UTC, schlimmchen requested changes
Thanks, looks good except for some details.

2024-11-01 20:37 UTC, schlimmchen commented on src/WebApi_ws_vedirect_live.cpp
> +        device["LOADCurrent"]["d"] = 2;
I also am not happy that we just copy the cryptic Victron abbreviations to the JSON, but please don't break the scheme. Use `IL` here.

2024-11-01 20:37 UTC, schlimmchen commented on src/WebApi_ws_vedirect_live.cpp
> +    }
I think we should publish it like this only if `IL` is available. Otherwise, if `IL` is not available but `LOAD` ist available, we display `mpttData.loadOutputState_LOAD.second` with a new label `VIRTLOAD` and add the respective texts/translations, as we then can assume that the device has a virtual load output, rather than (what you call) a physical load output. What do you think?

2024-11-02 06:53 UTC, SW-Niko commented on src/WebApi_ws_vedirect_live.cpp
> +        device["LOADCurrent"]["d"] = 2;
Ok, I will rename to "IL"

2024-11-02 07:19 UTC, SW-Niko commented on src/WebApi_ws_vedirect_live.cpp
> +    }
A good idea, but I assume it will not work on all devices.
I'm pretty sure I can also configure the virtual load output on any device with (physical) load output.
In that case IL is always available and I can not distinguish if I use virtual or physical load output.
I will check my assumption on my system today. Stay tuned.

2024-11-02 12:27 UTC, SW-Niko commented on src/WebApi_ws_vedirect_live.cpp
> +    }
Yes, if you have both then you can't distinguish which is used.
But anyway ... I like the idea. I think we can ignore this little disadvantage.
We just talk about the display in the web-view and keep MQTT and HASS like it is?

2024-11-03 09:15 UTC, schlimmchen commented on src/WebApi_ws_vedirect_live.cpp
> +    }
I think that it is very strange that those "smaller" models have both a physical and a virtual load output, but only a single property "LOAD". Therefore I would assume that the physical and virtual load output are always in sync. And therefore I don't think that it is even a problem that it says "load output" in the live view for models who have both a physical and a virtual load output. So yes, let's do this: Show "virtual load output state" if no IL but LOAD is available.

> We just talk about the display in the web-view and keep MQTT and HASS like it is?

Yes.

2024-11-03 17:03 UTC, SW-Niko commented on src/WebApi_ws_vedirect_live.cpp
> +    }
>Therefore I would assume that the physical and virtual load output are always in sync

Yes, they are.

Ok, I simulated different charger models
LOAD = true, IL = true
![grafik](https://github.com/user-attachments/assets/13839096-007a-495d-8f0c-436f6d80d7b9)
LOAD = true, IL = false
![grafik](https://github.com/user-attachments/assets/fd3da6ff-828c-4c34-8675-09e827dad375)
LOAD = false, IL = false
![grafik](https://github.com/user-attachments/assets/04cebcf0-921f-45ed-a527-12ea6109a529)

2024-11-03 18:46 UTC, schlimmchen approved these changes

2024-11-03 18:48 UTC, merged

2024-11-15 07:30 UTC, Cartman586 commented
@schlimmchen: eine kurze Frage, ist etwas bekannt (Hoymiles HMS-2000), wenn man von V01.00.27 auf V01.01.01.12 Updaten lässt, dass die 0% Einspeisung nicht mehr richtig funktioniert, oder ist da was bekannt und wurde gefixt? Danke

2024-11-15 09:07 UTC, Cartman586 commented
@schlimmchen @spcqike Danke für die Info, kann openDTU schon mit dieser neuen Firmware 01.01.12 und AC Ausgang Drosselung umgehen?

2024-11-15 09:12 UTC, spcqike commented
ich wüsste nicht, was dagegen spricht.

2024-11-15 09:18 UTC, Cartman586 commented
Hier wird beschrieben das er die neue Firmware ausprobiert hat aber die Regelung nicht mehr funktioniert hat
https://github.com/tbnobody/OpenDTU/discussions/2153#discussioncomment-11264484

2024-11-15 09:45 UTC, SW-Niko commented
Hallo @Cartman586 ,
wie @spcqike schon angemahnt hat.

>Was die Frage allerdings hier im PR sucht, noch dazu in einem, der sich mit etwas ganz anderem befasst, verstehe ich grade nicht.

Dein Thema ist in diesem PR "Off Topic". Sei so nett und führe dein Thema unter Discussions weiter.