Feature: Add VE.Direct "RELAY" to live view, MQTT, and HASS
hoylabs/OpenDTU-OnBattery pull request #1376
Opened 2024-11-07 10:37 UTC by SW-Niko

- process the "RELAY" information from the charger
- add to live view
- add to MQTT and HASS
Note: Only processed if available. Not all charger contain a fault relais

2024-11-07 10:44 UTC, SW-Niko commented
#1037 
Note: I did not implement "FWE" because according the Victron information "FWE" is only for "Phoenix Charger" and "Smart BuckBoost" and not for MPPT.

@schlimmchen : I do not have the right charger. Someone else must do the testing.

2024-11-13 21:14 UTC, schlimmchen requested changes
Thanks for this. The icon for HASS auto discovery is not a good choice, but otherwise this looks good. I can (mostly) test this with my father's charge controller.

2024-11-13 21:14 UTC, schlimmchen commented on src/MqttHandleVedirectHass.cpp
> +            publishBinarySensor("MPPT error relay state", "mdi:export", "RELAY", "ON", "OFF", *optMpptData);
Please use `mdi:electric-switch` as an icon: 
![image](https://github.com/user-attachments/assets/130df473-9b57-4334-8336-c6951a637ae3)

2024-11-13 21:19 UTC, schlimmchen commented
> Note: I did not implement "FWE" because according the Victron information "FWE" is only for "Phoenix Charger" and "Smart BuckBoost" and not for MPPT.

Can I motivate you to process and ignore "FWE" values and log a verbose message "FWE ignored"? I agree that we should ignore this, as it should not be there at all and if so, I expect it to be redundant to the other firmware info field. The benefit of explicitly ignoring the value is that we made the decision to ignore it and we make that clear by emitting a respective message, instead of suggesting that we don't know what FWE is. And we could then close #1037 as a whole :wink:

2024-11-14 12:34 UTC, SW-Niko commented
No problem. Can I do this weekend 😄

2024-11-18 15:51 UTC, SW-Niko commented on src/MqttHandleVedirectHass.cpp
> +            publishBinarySensor("MPPT error relay state", "mdi:export", "RELAY", "ON", "OFF", *optMpptData);
Done

2024-11-19 18:15 UTC, SW-Niko commented
Now we can get the firmware version from FW or FWE. 
All high level functions do not see any difference if version was transmitted by FE or FWE.
I think we can close #1037

2024-11-19 21:22 UTC, schlimmchen requested changes

2024-11-19 21:22 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +        if ((value.length() - 2) <= sizeof(_tmpFrame.firmwareVer_FW)) {
So if the device does not report FW, we still ignore FWE... I don't understand this if clause... We expect that the Victron device either sends only FW xor FWE, or that the two are equal. So we should process FWE unconditionally.

Have you checked what happens if the FWE string has a leading zero, which is optional:
![image](https://github.com/user-attachments/assets/a9bf5901-4c70-460a-89cf-c1051339af52)

2024-11-20 20:09 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +        if ((value.length() - 2) <= sizeof(_tmpFrame.firmwareVer_FW)) {
FYI: the line below, the use of strncpy, contains a possible write out of bounds. you cannot assume that the value's string minus two chars fits the target variable...

I will take care of that as well.

2024-11-20 21:45 UTC, schlimmchen commented
Tested successfully using https://github.com/schlimmchen/vedirect-mppt-emulator

2024-11-20 21:45 UTC, merged

2024-11-22 18:58 UTC, SW-Niko commented
Hello @schlimmchen ,
thanks for fixing my work. As always ... your work ist much more better. 👍