BREAKING CHANGE: remove default scaling/compensation for unused inputs
hoylabs/OpenDTU-OnBattery pull request #1473
Opened 2024-12-22 13:42 UTC by AndreasBoehm

Resolves parts of https://github.com/hoylabs/OpenDTU-OnBattery/issues/1472 by
- remove the default scaling/compensation for unused inputs 
- add hints why and when overscaling should be turned on or off

| Disabled | Enabled |
|----------|---------|
|![Screenshot 2024-12-22 at 14 41 06](https://github.com/user-attachments/assets/644596fb-0e98-4ea2-80fa-926366d76c15)|![Screenshot 2024-12-22 at 14 40 56](https://github.com/user-attachments/assets/0436911d-59d3-4622-a613-1b37b3b88c76)|

2024-12-22 13:58 UTC, AndreasBoehm commented
Hallo @FredonZen und @Jonrembo,

Ich hab in Absprache mit @schlimmchen eine Anpassung gemacht die euer Problem beheben sollte.

Bitte probiert es aus und gebt Bescheid ob sich euer Problem damit erledigt hat.

Das build zum testen könnt ihr euch hier herunterladen: https://github.com/hoylabs/OpenDTU-OnBattery/actions/runs/12454776481

Danke.

2024-12-22 15:00 UTC, AndreasBoehm commented
@FredonZen @Jonrembo

Mit dem build von hier https://github.com/hoylabs/OpenDTU-OnBattery/actions/runs/12455256044 seht ihr jetzt auch in der Wechselrichter Info (Startseite -> Wechselrichter Karte -> Zeige Wechselrichter-Info) ob wir korrekt erkannt haben das eure Wechselrichter Hoymiles 'Power Distribution Logic' unterstützen.

![Screenshot 2024-12-22 at 15 57 09](https://github.com/user-attachments/assets/7b77e8fc-8831-4727-beb3-73b365774f34)

2024-12-22 15:55 UTC, Jonrembo commented
euer support ist ja der Hammer!
Im Anhang die Screenshots! Funktioniert so wie es soll!
Vielen vielen dank 🙏 😊 
<img width="710" alt="Bildschirmfoto 2024-12-22 um 16 54 05" src="https://github.com/user-attachments/assets/d502effc-5a65-4d05-a043-6db246605143" />
<img width="1350" alt="Bildschirmfoto 2024-12-22 um 16 53 08" src="https://github.com/user-attachments/assets/82d66ecf-b294-492c-a799-a75d44d2e23e" />

2024-12-22 16:08 UTC, AndreasBoehm commented
Vielen Dank fürs testen und dein Feedback @Jonrembo

2024-12-22 20:19 UTC, schlimmchen requested changes
I don't think this is a breaking change. I thought the more elaborate overscaling method will effectively perform the same as the one we now removed?

2024-12-22 20:19 UTC, schlimmchen commented on webapp/src/views/PowerLimiterAdminView.vue
> +        },
Always return a boolean (always false except for the last return statement).

2024-12-22 20:19 UTC, schlimmchen commented on webapp/src/views/PowerLimiterAdminView.vue
> +                            v-html="$t('powerlimiteradmin.UseOverscalingInfo')"
This text is not defined?!

Indeed:
![image](https://github.com/user-attachments/assets/e4212151-f940-4510-bdcf-8b492c8bb01b)

Also, please align the alert similar to the one you show in the screenshot in the PR description about the minimum limit being too small.

2024-12-22 20:54 UTC, spcqike commented
> I don't think this is a breaking change. I thought the more elaborate overscaling method will effectively perform the same as the one we now removed?

isn’t the overscaling solar only and the „old“ scaling was always on and for all inverters/systems? So also for battery powered, when not all inputs where used? 

If so, it would break these setups, wouldn’t it?

2024-12-22 21:14 UTC, AndreasBoehm commented on webapp/src/views/PowerLimiterAdminView.vue
> +        },
Copy&paste 🙈  Fixed

2024-12-22 21:15 UTC, AndreasBoehm commented on webapp/src/views/PowerLimiterAdminView.vue
> +                            v-html="$t('powerlimiteradmin.UseOverscalingInfo')"
I forgot to remove this hint when i removed the text. Fixed

2024-12-22 21:17 UTC, AndreasBoehm commented
Actually the rework of the DPL was already a breaking change as the "old" scaling for unused inputs was removed from battery inverters.

I would still mark this change as breaking as its now also removing the "old" scaling for unused inputs from solar inverters for which this is a more likely use-case imho. Without manually enabling overscaling users with setups like these won't be able to get their inverter to cover their household usage.

2024-12-22 21:29 UTC, AndreasBoehm commented on lib/Hoymiles/src/inverters/HM_Abstract.h
> +    bool supportsPowerDistributionLogic() { return false; };
can't be final as its overwritten within `HMS_4CH.h`

2024-12-22 21:56 UTC, AndreasBoehm commented on lib/Hoymiles/src/inverters/HMS_4CH.h
> +    bool supportsPowerDistributionLogic();
fixed

2024-12-22 21:56 UTC, AndreasBoehm commented on src/PowerLimiterSolarInverter.cpp
> +                    _logPrefix, m + 'a', mpptPowerAC);
I did not check the existing code. Your suggestion makes sense, i hope i did what you meant.

2024-12-23 12:11 UTC, schlimmchen commented on lib/Hoymiles/src/inverters/HM_Abstract.h
> +    bool supportsPowerDistributionLogic() { return false; };
Ah yes, but then it's still `override` :wink:

2024-12-23 12:12 UTC, schlimmchen commented on lib/Hoymiles/src/inverters/HM_Abstract.h
> +    bool supportsPowerDistributionLogic() { return false; };
And you added that already. Resolved.

2024-12-23 12:20 UTC, schlimmchen approved these changes

2024-12-23 12:20 UTC, merged

2024-12-31 11:51 UTC, Josef1966 commented
Gibt es den build auch als "opendtu-onbattery-generic_esp32_4mb_no_ota.factory.bin"?

2024-12-31 14:17 UTC, schlimmchen commented
Dieser PR ist schon Teil des Development Branches. Nimm dir ein Artefakt aus einem der letzten "OpenDTU-OnBattery" Action Runs vom development Branch.

2025-01-01 08:32 UTC, Josef1966 commented
Ich bin da nicht so Experte bei diesem Thema. Wann kann man denn mit einem offiziellem Update rechnen?

2025-01-01 13:04 UTC, Exodusnick commented
> Gibt es den build auch als "opendtu-onbattery-generic_esp32_4mb_no_ota.factory.bin"?

Du musst die zip entpacken und da drin findest du auch die opendtu-onbattery-generic_esp32_4mb_no_ota.factory.bin

2025-01-01 13:20 UTC, Josef1966 commented
Habs gefunden und das DTU-Update schon gemacht. Jetzt werde ich mal schauen, ob es besser ist bzw. der Fehler mit der zu hohen Netzeinspeisung weg ist :-)
DANKE erst mal!

PS: wie findet man das Fenster "Inverter Info", wie weiter oben dargestellt?

2025-01-01 13:25 UTC, Exodusnick commented
> Habs gefunden und das DTU-Update schon gemacht. Jetzt werde ich mal schauen, ob es besser ist bzw. der Fehler mit der zu hohen Netzeinspeisung weg ist :-) DANKE erst mal!
> 
> PS: wie findet man das Fenster "Inverter Info", wie weiter oben dargestellt?

![IMG_20250101_142443_490](https://github.com/user-attachments/assets/0a89f78b-729d-4308-974a-28cdb1e00c23)

2025-01-01 13:30 UTC, Josef1966 commented
.... oh Mann, da hätte ich ja selber drauf kommen können. Da steht jetzt bei mir auch 'Power Distribution Logic' unterstützt: ja  - es scheint also zu funktionieren :-)

2025-01-07 16:58 UTC, AndreasBoehm commented
Komisch das bei einem Limit von 96W nur 45W produziert werden, die neue WR Firmware 01.01.12 hast du drauf, ja?

Gibt es eine Limitierung des Akkus?

Warum nutzt du denn nicht alle vier Eingänge?

Sonst versuchs auch mal das du den Inverter als Batteriebetrieben konfigurierst im DPL.

Bitte probier es sonst auch nochmal mit diesem build, da habe ich nochmal etwas angepasst im Bezug auf Solarbetrieben WRs: https://github.com/hoylabs/OpenDTU-OnBattery/actions/runs/12640038459

2025-01-07 17:06 UTC, Exodusnick commented
https://github.com/Josef1966
(zendure 2000 + 5 Akkus)
Habe das selbe Problem aber nur wenn 
Wechselrichter von Solarmodule gespeichet wird.

So läuft das bei mir und und kann so eine Nulleinspeisung erreichen 

![Screenshot_2025-01-07-18-02-24-492_com android chrome](https://github.com/user-attachments/assets/3ad4a015-c0a4-4778-a4a7-8a7d05386c41)
![Screenshot_2025-01-07-18-00-51-348_com android chrome](https://github.com/user-attachments/assets/9733cd32-5471-4638-ab01-af1a6d363dac)
![Screenshot_2025-01-07-17-55-52-817_com android chrome](https://github.com/user-attachments/assets/3b9a6e28-da92-4f44-af9d-bc18db60d001)
![Screenshot_2025-01-07-17-55-39-851_com android chrome](https://github.com/user-attachments/assets/e8f398e5-bcdf-486a-8e30-a0ac4496fe83)

2025-01-07 17:23 UTC, Exodusnick commented
https://github.com/user-attachments/assets/418cc1d8-c97a-4c72-809e-82e01f51a4d3

2025-01-07 17:25 UTC, AndreasBoehm commented
@Exodusnick und bei dir nimmt sich der WR dann über nur zwei Eingänge genug Leistung? bzw dann eben nicht genug wenn du den WR als Solargespeist angibst?
Also das kann ja grundsätzlichs nichts mit dem Betriebsmodus "Solar" oder "Batterie" zutun haben wenn der WR sich nicht genug Leistung nimmt bzw die Batterie nicht genug liefert.

Limit von 96W sollte auch 96W Ausgabe bedeuten wenn der WR die aktuelle Firmware hat und die Batterie genug liefert.

2025-01-07 17:27 UTC, Josef1966 commented
Ja, die neue Firmware ist drauf:
![WR](https://github.com/user-attachments/assets/fe34b368-f71c-4b1c-bc2b-2cac85e53f90)

Akku bzw. Solarflow Hub ist auf Maximum-Output (1200 W) gestellt.

2025-01-07 17:33 UTC, Exodusnick commented
Wie oben geschrieben 

> @Exodusnick und bei dir nimmt sich der WR dann über nur zwei Eingänge genug Leistung? bzw dann eben nicht genug wenn du den WR als Solargespeist angibst? Also das kann ja grundsätzlichs nichts mit dem Betriebsmodus "Solar" oder "Batterie" zutun haben wenn der WR sich nicht genug Leistung nimmt bzw die Batterie nicht genug liefert.
> 
> Limit von 96W sollte auch 96W Ausgabe bedeuten wenn der WR die aktuelle Firmware hat und die Batterie genug liefert.

Ja über zwei Eingänge nimmt er genug Leistung, wenn Wechselrichter wird von Solarmodule gespeicht "deaktiviere" ist . Aktiviere ich es
Funktioniert es nicht und ich bekomme kein Nulleinspeisung zustande.

2025-01-07 17:41 UTC, Josef1966 commented
> Komisch das bei einem Limit von 96W nur 45W produziert werden, die neue WR Firmware 01.01.12 hast du drauf, ja?
Ja
> 
> Gibt es eine Limitierung des Akkus?
Nein
> 
> Warum nutzt du denn nicht alle vier Eingänge?
Werde ich demnächst versuchen, brauche nur noch neue Kabel, um alle 4 Eingänge mit gleich langen Kabeln anschließen zu können.
> 
> Sonst versuchs auch mal das du den Inverter als Batteriebetrieben konfigurierst im DPL.
Versuche ich auch mal, wie von [Exodusnick](https://github.com/Exodusnick) beschrieben.
> 
> Bitte probier es sonst auch nochmal mit diesem build, da habe ich nochmal etwas angepasst im Bezug auf Solarbetrieben WRs: https://github.com/hoylabs/OpenDTU-OnBattery/actions/runs/12640038459
Ok, mache ich auch :-)

2025-01-07 17:46 UTC, AndreasBoehm commented
> Ja über zwei Eingänge nimmt er genug Leistung, wenn Wechselrichter wird von Solarmodule gespeicht "deaktiviere" ist . 

Wir reden hier denke ich über zwei verschieden Dinge.

a) WR setzt das eingestellt Limit um (wie oben aufgezeigt liefert der WR nur 45W obwohl das Limit auf 96W steht)
b) DTU fordert die gewünschte Leistung an um eine Nulleinspeisung zu realisieren (Das tut die DTU nicht wenn **a)** nicht erfüllt wird)

Auf **a)** hat man keinen Einfluss, egal ob du den WR für den Solar- oder Batteriebetrieb konfiguriert hast.
Der Unterschied ist nur das die DTU im Batteriebetrieb einfach stumpf ein Limit setzt, egal ob **a)** erfüllt ist oder nicht.

@schlimmchen Sollten wir `maxIncrease` auch im Solarbetriebe einfach immer das maximale Inverter Limit zurück geben lassen für den fall das nur ein einzelner Inverter konfiguriert ist? Das würde uns einige Probleme ersparen. Die echte Berechnung ist ja tatsächlich nur relevant wenn es mehr als einen Inverter gibt.

2025-01-07 17:55 UTC, Josef1966 commented
@Exodusnick
Nach welchen Kriterien stellst du die Batterie Spannungs-Schwellwerte "Batterienutzung Start-Schwellwert", "Batterienutzung Stop-Schwellwert" und "Lastkorrekturfaktor" ein?
Muss man dann auch im Abschnitt "Batterie" Einstellungen ändern oder kann man dort alles deaktiviert lassen?

2025-01-07 17:58 UTC, AndreasBoehm commented
@Exodusnick Willst du deine Einstellungsempfehlung hier im [Wiki des Projekts](https://github.com/hoylabs/OpenDTU-OnBattery/wiki) veröffentlichen, als Anleitung für alle anderen Zendure Nutzer?

2025-01-07 18:01 UTC, Exodusnick commented
> @Exodusnick Willst du deine Einstellungsempfehlung hier im [Wiki des Projekts](https://github.com/hoylabs/OpenDTU-OnBattery/wiki) veröffentlichen, als Anleitung für alle anderen Zendure Nutzer?

Würde ich gerne machen hab derzeit nicht wirklich Zeit .
Könntest du das für mich erledigen?
Das wäre super nett.👍

2025-01-07 19:01 UTC, Exodusnick commented
> > @Exodusnick Willst du deine Einstellungsempfehlung hier im [Wiki des Projekts](https://github.com/hoylabs/OpenDTU-OnBattery/wiki) veröffentlichen, als Anleitung für alle anderen Zendure Nutzer?
> 
> Würde ich gerne machen hab derzeit nicht wirklich Zeit . 
Eventuell könnte ich am Wochenende ein wenig Zeit investieren.

2025-01-07 19:10 UTC, AndreasBoehm commented
> Und wie kommt diese Info in die PowerLimiterSolarInverter Istanz? Das wird so hässlich und gekoppelt, dass ich mich erstmal dagegen wehren möchte...


Ja das stimmt, das sollten wir wirklich nicht tun 🙈

> Hattest du nicht vorgeschlagen, immer mind. "aktuelle Leistung plus Offset" zurückzugeben für maxIncrease? Offset beispielsweise 3% der Maximalleistung oder so?

Ich meinte was anderes, deine Idee find ich aber sehr gut. Das sollte klappen. Mach ich heute oder morgen noch fertig für das kommende release.

2025-01-08 09:22 UTC, AndreasBoehm commented
@Josef1966 Ich hab nochmal einen PR erstellt der vermeidet das der WR bei einem zu niedrigen Limit hängen bleibt (Wenn der WR als Solarbetrieben konfiguriert ist)

Bitte gib Bescheid ob das dein Problem löst: https://github.com/hoylabs/OpenDTU-OnBattery/pull/1507

2025-01-08 15:03 UTC, Exodusnick commented
> @Exodusnick nach welchen Kriterien stellst du die Batterie Spannungs-Schwellwerte "Batterienutzung Start-Schwellwert", "Batterienutzung Stop-Schwellwert" und "Lastkorrekturfaktor" ein? Muss man dann auch im Abschnitt "Batterie" Einstellungen ändern oder kann man dort alles deaktiviert lassen?

Batterie kannst du deaktiviert lassen, nur Bei Batterie Spanungs schwellwert ändern .
Siehe vorletztes Screenshot.
Und beim letzten Screenshot die 1 gewählt.

2025-01-08 15:21 UTC, Josef1966 commented
> @Josef1966 Ich hab nochmal einen PR erstellt der vermeidet das der WR bei einem zu niedrigen Limit hängen bleibt (Wenn der WR als Solarbetrieben konfiguriert ist)
> 
> Bitte gib Bescheid ob das dein Problem löst: #1507

.... super, danke :-) Ich werde es die nächsten Tage testen.

2025-01-09 13:44 UTC, Josef1966 commented
Ich habe den test build 1507 ausprobiert und bisher läuft es problemlos. Ich habe auch noch den "Batterie-Betrieb" von Exodusnick getestet, auch diese Version scheint zu laufen.
Den einzigen Unterschied, den ich gesehen habe ist der, dass beim Batterie-Betrieb das gesetzte "aktuelle Limit" bis auf 1600W hochgeht und beim Solarbetrieb nur bis 800W. In beiden Versionen wird aber trotzdem nur max. 800 Watt eingespeist, was bei nur 2 belegten WR-Eingängen ja auch richtig ist.
Ich habe mir jetzt noch gleich lange Kabel für die Verbindung Hub-WR besorgt, so dass ich in Kürze auch noch die 4-fach Belegung des WR unter den beiden Varianten testen kann.

2025-01-09 15:45 UTC, Exodusnick commented
Den einzigen Unterschied, den ich gesehen habe ist der, dass beim Batterie-Betrieb das gesetzte "aktuelle Limit" bis auf 1600W hochgeht 

Kann nicht sein ich hab den hoymiles 2000 nur zwei Eingänge belegt den hub auf volle Leistung Gestell (1,2kw)
Und der Wechselrichter geht nur bis 1kw 

Schau der gibt nur 1000 watt .

Uploading VID_20250109_164433_538.mp4…

2025-01-09 15:47 UTC, Exodusnick commented
https://github.com/user-attachments/assets/93078a63-ceba-47d8-9f73-835464d2f0bf

2025-01-09 17:56 UTC, spcqike commented
> Kann nicht sein ich hab den hoymiles 2000 nur zwei Eingänge belegt den hub auf volle Leistung Gestell (1,2kw)
Und der Wechselrichter gibt nur bis 1kw

Aber auch dein WR steht auf 2000W. 
Er hat schon recht. Die Firmware scheint noch immer zu skalieren, da ihr nicht beide Eingänge belegt habt. 

Das wäre wohl mit der neuen Firmware nicht nötig. Schadet so aber auch grade nicht.

2025-01-16 13:47 UTC, Josef1966 commented
@Exodusnick warum nutzt du eigentlich nur 2 und nicht alle 4 Eingänge an deinem HMS-2000?

2025-01-19 10:48 UTC, Josef1966 commented
Hallo @AndreasBoehm @Exodusnick 
Ich habe jetzt den HMS-1600 mit 4 identischen Kabeln mit dem Zendure Hub verbunden und siehe da, die Leistungsverteilung ist jetzt ziemlich gleichmässig :-)

Die DPL habe ich auf Batterie-Betrieb ("Wechselrichter wird von Solarmodulen gespeist" deaktiviert) umgestellt und heute habe ich bei guter Sonne geschaut, wie es läuft. Leider sehr enttäuschend, weil die DPL nicht die geforderte Leistung einspeist.

Bei hohem Verbrauch >2kW fordert die DPL zwar das Maximum (1600W) an, der WR liefert aber nur <100W Leistung, obwohl der Zendure-Akku nahezu komplett aufgeladen ist.

Könnt ihr den Fehler aus den anhängenden Daten auslesen?

![openDTU-live_battery](https://github.com/user-attachments/assets/54349cbb-aaf6-4728-8c03-ab0b1924a0c5)
![OpenDTU_Ereignisanzeige](https://github.com/user-attachments/assets/7f796a57-b98b-46f5-b8b3-79f40c0e0219)
![OpenDTU_System-Info](https://github.com/user-attachments/assets/e4d59394-fad6-45ed-b5cf-3a237c0cb048)
![WR-Info](https://github.com/user-attachments/assets/13474ce9-50a0-4e57-a727-c52e2f1c9c9c)

[Log.txt](https://github.com/user-attachments/files/18468511/Log.txt)

2025-01-19 11:40 UTC, AndreasBoehm commented
@Josef1966 Das limit steht auf 1600W, der Akku liefert 64W. Da können wir nichts tun. Das Problem liegt auf WR oder Akku Seite.

Der DPL setzt ein Limit das zum aktuellen Stromverbrauch laut Powermeter passt, hier 1600W. Mehr tut der DPL nicht.

2025-01-19 12:24 UTC, Josef1966 commented
@AndreasBoehm Ich habe aber auch solche Zustände, also Limit deutlich niedriger als Leistung.
![openDTU-live_battery](https://github.com/user-attachments/assets/96908901-4eb8-46fc-89ba-1aed08e4779b)

Hier der Log dazu:
https://pastebin.com/XXjViUf1

2025-01-19 15:25 UTC, Exodusnick commented
So schaut es bei mir aus Hub ins aus auf Maximum wr alle 4 Eingänge belegt 
DPL Einspeisung von Modulen deaktiviert.
Besser geht die Nulleinspeisung nicht.

Werde gleich mit Einspeisung von Modulen post 

Uploading VID_20250119_161717_205.mp4…

2025-01-19 15:26 UTC, Exodusnick commented
https://github.com/user-attachments/assets/dbca8344-3492-475f-96a1-f3089eb150f8

2025-01-19 15:34 UTC, Exodusnick commented
So und hier DPL mit Einspeisung über Solarmodule 

https://github.com/user-attachments/assets/f668b110-3892-4351-8225-7c9bea6c6d51

2025-01-19 15:43 UTC, Exodusnick commented
https://github.com/user-attachments/assets/aa9ecc9c-59c1-43ae-94cc-f9b660b4e8b1

2025-01-19 18:40 UTC, Josef1966 commented
Wie erklärst du die Unterschiede bei der Leistungsverteilung auf die 4 WR-Eingänge?

Bei Batteriebetrieb hast du: 49W - 56W- 185W - 216W, also string 3 und 4 deutlich höher als string 1 und 2
Mei Modul-Betrieb sieht es dem gegenüber relativ gleichmässig aus: 40W - 45W - 46W - 54W

Kann das jemand erklären und wenn ja, warum funktioniert das dann bei Exodusnick?

Ich habe bei mir mit 4 Eingängen am WR keine vernünftige Steuerung realisieren können, auch nicht im Batteriebetrieb.
Bin dann zurück auf 2 Eingänge (1 + 3) gegangen, dann hat es gut funktioniert, aber eben nur mit max Ausgangsleistung = 800W.
Habe dann noch string 4 dazugenommen und es hat weiterhin funktioniert, aber dann mit max 1200W.
Wäre schön, wenn es eine Erklärung gäbe, warum das jetzt mit 3 Eingängen, aber nicht mit 4 Eingängen funktioniert.

2025-01-19 18:59 UTC, AndreasBoehm commented
> @AndreasBoehm Ich habe aber auch solche Zustände, also Limit deutlich niedriger als Leistung.
> 
> ![openDTU-live_battery](https://private-user-images.githubusercontent.com/164872227/404662736-96908901-4eb8-46fc-89ba-1aed08e4779b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczMTMzMjQsIm5iZiI6MTczNzMxMzAyNCwicGF0aCI6Ii8xNjQ4NzIyMjcvNDA0NjYyNzM2LTk2OTA4OTAxLTRlYjgtNDZmYy04OWJhLTFhZWQwOGU0Nzc5Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExOVQxODU3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzNlYmMzODAwZjNhZjRlZDU1M2FiMDQyMzJkMjA5ZGI3MDk1YmI1MmZjMGUwNDFjOTU4ZDMxM2NkZTIyZDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RkWG4HdmL9gKpDtUvwCDTOKXc0Y7xRJytfS1CSwexgQ)
> 
> Hier der Log dazu: https://pastebin.com/XXjViUf1

Betrieb als Solarbetrieben ist bei dir nicht zielführend, da es hierfür wichtig ist das der Akku das liefert was wir als limit setzen. Bitte leg dich auf eine Betriebsweise fest und bleib dabei. Das ist nicht zielführend wenn du in jedem Kommentar über eine andere Betriebsart sprichst.

2025-01-19 19:02 UTC, AndreasBoehm commented
@Josef1966 Kannst du mal die Einstellungen deines Akkus un eventuell auch Live Daten des Akkus zeigen?

Dann kannst du auch besser mit @Exodusnick vergleichen.

2025-01-19 19:10 UTC, Josef1966 commented
> @Josef1966 Kannst du mal die Einstellungen deines Akkus un eventuell auch Live Daten des Akkus zeigen?
> 
Die Einstellungen in der Zendure-App meinst du?

2025-01-20 06:05 UTC, AndreasBoehm commented
> Die Einstellungen in der Zendure-App meinst du?

Jap

2025-01-21 11:46 UTC, Exodusnick commented
> @Exodusnick
> 
> Wie erklärst du die Unterschiede bei der Leistungsverteilung auf die 4 WR-Eingänge?
> 
> Bei Batteriebetrieb hast du: 49W - 56W- 185W - 216W, also string 3 und 4 deutlich höher als string 1 und 2 Mei Modul-Betrieb sieht es dem gegenüber relativ gleichmässig aus: 40W - 45W - 46W - 54W
> 
Lieg wahrscheinlich daran das ich zwei Hub's benutzt habe für den Test, zweifach mc4 Stecker am hub 1 und zwei. 1 und 3 hub1 2 und 4 hub2 und so die mppt besser zusammen arbeiten können.......
Wenn ich ein Hub an alle 4 anschließe mit vierfach mc4 Stecker funktioniert es bei mir auch nicht vernünftig.
Bin der Meinung das es an den mppt liegt die sich gegenseitig stören bei vierfach mc4 Stecker zum WR .

2025-01-21 22:40 UTC, Exodusnick commented
> @Exodusnick Willst du deine Einstellungsempfehlung hier im [Wiki des Projekts](https://github.com/hoylabs/OpenDTU-OnBattery/wiki) veröffentlichen, als Anleitung für alle anderen Zendure Nutzer?

Diese Anleitung wäre super für Einstellungsempfehlung auf Wiki....
https://github.com/hoylabs/OpenDTU-OnBattery/pull/1473#issuecomment-2604680142 👍

2025-01-22 09:03 UTC, Josef1966 commented
@Exodusnick
Die Anleitung kann gerne dort im Wiki hinterlegt werden . Ich weiß nur nicht, wie man das (korrekt) macht - vielleicht kann des jemand von den Experten übernehmen?